/******************************************************************************************
 *  ERP_MARK7 -  BankReconciliation
 *
 *  Purpose : Called when Upload Button for Importing CSV(BANK STATEMENT) File is Clicked.
 *  Author  : Aqxolt - Arshadulla Shariff
 *  Started Date    : 2015-05-25
 *  End Date        :
 *  Version : 1.0
 *  Project : ERP_MARK7
 *  
 *      - This Class Manages import Bank Statement(csv format) and Inserts Data into Object(BankStatement__c)
 *      
 *  
 *  Modification History
 *  Date         Who      Ver   Description  
 *  yyyy-mm-dd - XX - XX - xxxxxxxxxxxxxxxxxxxxxxxxxxxx
 *
 * 
 ********************************************************************************************/
public with sharing class BankReconciliation {

}